force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LegalAdvisors__c/LegalAdvisors__c.object-meta.xml
<CustomObject>
    <label>Legal Advisor</label>
    <nameField>
        <label>LegalAdvisors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LegalAdvisors__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LegalAdvisors__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_UpsertAdvisors.cls
public with sharing class ucl_UpsertAdvisors {
    @AuraEnabled(cacheable=true) 
    public static void UpsertAdvisors() {
        //http call for response 
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://altimetrik-bootcamp.herokuapp.com/LegalAccounts');
        req.setMethod('GET');
        HttpResponse res = http.send(req);

        List<LegalAdvisors__c> legalAdvisorsToUpsert = new list<LegalAdvisors__c>();	

        //if status code ok proceed
        if (res.getStatusCode() == 200) {
        List<Object> objects = (List<Object>) JSON.deserializeUntyped(res.getBody());                                  
         for (Object obj: objects) {
        // map to get value and key on advisors
          Map<String, Object> mapLAdvisorsData = (Map<String, Object>)obj;      
        // ckecking advisors status        
                    if((string) mapLAdvisorsData.get('AccountStatus') == 'Enabled') { // unico cambio a testear string en la condicion
                        // mapping data
                       LegalAdvisors__c legalAdvisor = new LegalAdvisors__c();             
                       legalAdvisor.Account_Name__c = (String) mapLAdvisorsData.get('AccountName');
                       legalAdvisor.Name = (String) mapLAdvisorsData.get('AccountName');
                       legalAdvisor.Account_Number__c =  (String) mapLAdvisorsData.get('AccountNumber');
                       legalAdvisor.Account_Status__c = (String) mapLAdvisorsData.get('AccountStatus');
                       string asOfDate = (string) mapLAdvisorsData.get('AsOfDate');
                       String[] dateParts = asOfDate.split('/');
                       Integer year = Integer.valueOf(dateParts[2]);
                       Integer month = Integer.valueOf(dateParts[0]);
                       Integer day = Integer.valueOf(dateParts[1]);
                       legalAdvisor.As_of_Date__c = Date.newInstance(year, month, day);
                       legalAdvisorsToUpsert.add(legalAdvisor);
                }     
            }             
        }
        
        //upsert data or create error
        try {
            upsert legalAdvisorsToUpsert Account_Number__c;
            
            system.debug('Todo salio bien');
        } catch (DmlException e) {
           Error_Log__c customError = new Error_Log__c();
           customError.ErrorMessage__c = e.getMessage();
            insert customError;
           System.debug(e.getMessage());
         }          
    }
}