force-app/main/default/objects/LegalAdvisors__c/LegalAdvisors__c.object-meta.xml
<CustomObject>
    <label>Legal Advisor</label>
    <nameField>
        <label>LegalAdvisors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LegalAdvisors__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LegalAdvisors__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_LegalAdvisors.cls
public class ucl_LegalAdvisors {
	@AuraEnabled(cacheable=true)
	public static void getLegalAdvisorsData() {
		Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://altimetrik-bootcamp.herokuapp.com/LegalAccounts');
        req.setMethod('GET');
        HttpResponse res = http.send(req);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        // If status code is ok, create a list of objects and desearlize them to get single data
		if (res.getStatusCode() == 200) {
		   List<Object> objects = (List<Object>) JSON.deserializeUntyped(res.getBody());
            List<String> accountNumberList = new List<String>(); // unica linea agregada que esta a prueba
		   List<LegalAdvisors__c> oldAdvisorList = [SELECT Id, Account_Number__c, Account_Status__c 
                                        FROM LegalAdvisors__c 
                                        WHERE Account_Number__c 
                                        IN : accountNumberList];// hasta aqui agregado de prueba
            system.debug(oldAdvisorList);
            for (Object obj: objects) {
		   Map<String, Object> mapLAdvisorsData = (Map<String, Object>)obj;
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            
            if ((String) mapLAdvisorsData.get('AccountStatus') == 'Enabled') {
                
                for(LegalAdvisors__c oldAdvisor: oldAdvisorList) {
                if(oldAdvisor.Account_Number__c == (String) mapLAdvisorsData.get('AccountNumber')) {
                    system.debug(oldAdvisor);
                    oldAdvisor.Account_Name__c = 'MAn';
                    oldAdvisor.Name = (String) mapLAdvisorsData.get('AccountName');
		            oldAdvisor.Account_Number__c =  (String) mapLAdvisorsData.get('AccountNumber');
		            oldAdvisor.Account_Status__c = (String) mapLAdvisorsData.get('AccountStatus');
                    //oldAdvisor.As_of_Date__c =  Date.parse( mapLAdvisorsData.get('AsOfDate'));
                    update oldAdvisor;
                    accountNumberList.add(OldAdvisor.Account_Number__c);
                    
                }
                    
                          
                }
            
                                                      
       
            
          
            
            
            }
          
         }
 }
	}
    }