force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Client Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Client__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Legal_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Advisor</label>
    <referenceTo>LegalAdvisors__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LegalAdvisors__c/LegalAdvisors__c.object-meta.xml
<CustomObject>
    <label>Legal Advisor</label>
    <nameField>
        <label>LegalAdvisors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LegalAdvisors__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LegalAdvisors__c/fields/Created_by_Syster_Admin__c.field-meta.xml
<CustomField>
    <fullName>Created_by_Syster_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created by Syster Admin?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ucl_UpsertClients.cls
public with sharing class ucl_UpsertClients {
    @AuraEnabled(cacheable=true) 
    public static void UpsertClients() {
      
      Http http = new Http();
      HttpRequest req = new HttpRequest();
      req.setEndpoint('https://altimetrik-bootcamp.herokuapp.com/LegalAccounts');
      req.setMethod('GET');
      HttpResponse res = http.send(req);

      ucl_UpsertAdvisors.UpsertAdvisors();

       List<Client__c> ClientsToUpsert = new list<Client__c>();
       List<Client__c> ClientsToDelete = new list<Client__c>();
       
       List<LegalAdvisors__c> legalAdvisors = [Select Id, Account_Number__c
                                              From LegalAdvisors__c];

      if (res.getStatusCode() == 200) {
      List<Object> objects = (List<Object>) JSON.deserializeUntyped(res.getBody());
                                  
       for (Object obj: objects) {
       Map<String, Object> mapLAdvisorsData = (Map<String, Object>)obj;      
                  
       if((String) mapLAdvisorsData.get('AccountStatus') == 'Enabled') {
           for(LegalAdvisors__c legalA : legalAdvisors) {
                   if(legalA.Account_Number__c == (string)mapLAdvisorsData.get('AccountNumber')) {
           List<Object> clients = (List<Object>)mapLAdvisorsData.get('Clients');
           for(object client:clients){
           Map<String, Object> mapClientsData = (Map<String, Object>)client;
               
                       
                       Client__c cl = new Client__c();
                       cl.First_Name__c = (string) mapClientsData.get('FirstName');
                       cl.Last_Name__c = (string) mapClientsData.get('LastName');
                       cl.Email__c = (string) mapClientsData.get('Email');
                       cl.Address__c = (string) mapClientsData.get('Address');
                       cl.Phone__c = (string) mapClientsData.get('Phone');
                       cl.Client_Number__c = (string) mapClientsData.get('ClientNumber');
                       cl.Legal_Advisor__c = legalA.id;
                       cl.Name = (string) mapClientsData.get('FirstName') + ' ' + (string) mapClientsData.get('LastName');
                       ClientsToUpsert.add(cl);
                   }
               }
              }     
          }             
      }
      }

List<String> ClientNumbers = new List<String>();
for(Client__c c : ClientsToUpsert) {
  ClientNumbers.add(c.Client_Number__c);
}

List<Client__c> ClientsNotInJson = [SELECT id, Client_Number__c, Created_by_Syster_Admin__c, Name  FROM Client__c WHERE Client_Number__c NOT IN : ClientNumbers];
for(Client__c ClientToDelete : ClientsNotInJson) {
    if(!ClientToDelete.Created_by_Syster_Admin__c) {
        ClientsToDelete.add(ClientToDelete);
    }
}
system.debug(ClientsToDelete);

        try {
          upsert ClientsToUpsert Client_Number__c;
          delete ClientsToDelete;
          system.debug('Todo salio bien con clients');
        } catch (DmlException e) {
            Error_Log__c customError = new Error_Log__c();
            customError.ErrorMessage__c = e.getMessage();
            insert customError;
          System.debug(e.getMessage());
        }
        }
    }