force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Client Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Client__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/ID_client_contract__c.field-meta.xml
<CustomField>
    <fullName>ID_client_contract__c</fullName>
    <formula>External__r.Account_Number__c  &amp;  Client_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID client contract</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LegalAdvisors__c/LegalAdvisors__c.object-meta.xml
<CustomObject>
    <label>Legal Advisor</label>
    <nameField>
        <label>LegalAdvisors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LegalAdvisors__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LegalAdvisors__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_QueryData.cls
public with sharing class ucl_QueryData {

    @AuraEnabled(cacheable=true)
    public static List<LegalAdvisors__c> showLegalAdvisorData() {
        List<LegalAdvisors__c> la= [SELECT Account_Name__c,
                                     Account_Number__c,
                                     Account_Status__c, 
                                     As_Of_Date__c 
                                     FROM LegalAdvisors__c WHERE Account_Status__c != 'Disabled'];
         system.debug(la);
         return(la);
    }

    @AuraEnabled(cacheable=true)
    public static List<Client__c> showClientData() {
        List<Client__c> lc =  [SELECT  First_Name__c,
                                       Client_Number__c,
                                       Last_Name__c, 
                                       Email__c, 
                                       Phone__c, 
                                       Address__c 
                                       //ID_client_contract__c 
                                       FROM Client__c];
         system.debug(lc);
         return(lc);
    }
}