force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Client Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Client__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Legal_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Advisor</label>
    <referenceTo>LegalAdvisors__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LegalAdvisors__c/LegalAdvisors__c.object-meta.xml
<CustomObject>
    <label>Legal Advisor</label>
    <nameField>
        <label>LegalAdvisors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LegalAdvisors__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/LegalAdvisors__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_httpRequestAndMappingData.cls
public with sharing class ucl_httpRequestAndMappingData {

    public static void ucl_httpRequestAndMappingData() {
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://altimetrik-bootcamp.herokuapp.com/LegalAccounts');
        req.setMethod('GET');
        HttpResponse res = http.send(req);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////














        

List<String> accountNumberList = new List<String>();

        

        // If status code is ok, create a list of objects and desearlize them to get single data
//////////////////////////////////////////////////////////////////////////////////////////////////////////////
		if (res.getStatusCode() == 200) {
		   List<Object> objects = (List<Object>) JSON.deserializeUntyped(res.getBody());
		for (Object obj: objects) {
		   Map<String, Object> mapLAdvisorsData = (Map<String, Object>)obj; //==> devuelve todos los advisors y clients con clave valor
/////////////////////////////////////////////////////////////////////////////////////////////


for(LegalAdvisors__c advisor : newAdvisors){
   accountNumberList.add(advisor.Account_Number__c);
}
        
        
List<LegalAdvisors__c> oldAdvisorList = [SELECT Id, Account_Number__c 
                                        FROM LegalAdvisors__c 
                                        WHERE Account_Number__c 
                                        IN : accountNumberList];










           




////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                                            
LegalAdvisors__c legalAdvisor = new LegalAdvisors__c(); 
legalAdvisor.Account_Name__c = (String) mapLAdvisorsData.get('AccountName');
legalAdvisor.Name = (String) mapLAdvisorsData.get('AccountName');
legalAdvisor.Account_Number__c =  (String) mapLAdvisorsData.get('AccountNumber');
legalAdvisor.Account_Status__c = (String) mapLAdvisorsData.get('AccountStatus');
//legalAdvisor.As_of_Date__c =  Date.parse( mapLAdvisorsData.get('AsOfDate'));
    system.debug(legalAdvisor);// hasta aqui codigo impecable
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////       

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////       
List<Object> clients = (List<Object>)mapLAdvisorsData.get('Clients');
    for(object client:clients){
        Map<String, Object> mapClientsData = (Map<String, Object>)client;
        system.debug(mapClientsData);

        
        Client__c cl = new Client__c();
        cl.First_Name__c = (string) mapClientsData.get('FirstName');
        cl.Last_Name__c = (string) mapClientsData.get('LastName');
        cl.Email__c = (string) mapClientsData.get('Email');
        cl.Address__c = (string) mapClientsData.get('Address');
        cl.Phone__c = (string) mapClientsData.get('Phone');
        cl.Client_Number__c = (string) mapClientsData.get('ClientNumber');
        cl.Legal_Advisor__c = (String) mapLAdvisorsData.get('AccountNumber');
        cl.Name = (string) mapClientsData.get('FirstName') + (string) mapClientsData.get('LastName');// esto tambien solo falta resolver campo externo
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                
               }
           }
        }
    }
}